name: CI
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**
jobs:
  name: first_job
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v4